#24 Adding functionality to add a movie to favorites and show on the …
DanMir0/Movies-app pull request #25
Opened 2024-03-25 16:17 UTC by DanMir0

2024-04-15 19:43 UTC, kalex375 requested changes
https://app.screencastify.com/v3/watch/zxMkpcYlQmONhvaGfFuZ

2024-04-17 12:37 UTC, DanMir0 commented
у меня все ок

2024-04-17 21:42 UTC, kalex375 commented
> у меня все ок

если я не залогинен то как должно работать?

2024-04-21 10:41 UTC, kalex375 requested changes

2024-04-21 10:41 UTC, kalex375 commented on src/components/MovieItem.vue
> +        if (Object.keys(user.value).length !== 0) {
это очень странная проверка.  проверь просто user.value.email

2024-04-23 17:03 UTC, merged