#28 fix pagination
DanMir0/Movies-app pull request #29
Opened 2024-04-16 20:38 UTC by DanMir0

2024-04-17 21:52 UTC, kalex375 requested changes
Хорошо только rote link в пагинации нужно поправить

2024-04-17 21:52 UTC, kalex375 commented on src/components/UI/MaPagination.vue
> +                <router-link
так а смысл от этого router-link если адрес все еще #
```
<RouterLink to="YourFilerRouteName" :query="{ page: currentPage }">

2024-04-21 10:39 UTC, kalex375 requested changes

2024-04-21 10:39 UTC, kalex375 commented on src/components/UI/MaPagination.vue
> +                <router-link to="/" :query="{page: props.page + 1}" @click="$emit('change', props.page + 1)">Next</router-link>
ckзачем тут клик?

2024-04-22 12:43 UTC, DanMir0 commented on src/components/UI/MaPagination.vue
> +                <router-link to="/" :query="{page: props.page + 1}" @click="$emit('change', props.page + 1)">Next</router-link>
чтобы страницу передавать

2024-04-23 11:56 UTC, kalex375 approved these changes

2024-04-23 17:03 UTC, merged